name: telegram_clone
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  pinput: ^2.2.12
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  google_fonts: ^3.0.1
  file_picker: ^5.0.1
  image_picker: ^0.8.5+3
  provider: ^6.0.4
  shared_preferences: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
